from immu.collections_base import ImmuSequence, EmptyCollectionError

trait Stack(ImmuSequence):
    def push(self, value: Self._VT) -> Self: ...
    def pop(self) raises EmptyCollectionError -> Tuple[Self._VT, Self]: ...
    def top(self) raises EmptyCollectionError -> Self._VT: ...