[workspace]
authors = ["Tomás Silveira Salles <tomasssalles@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "immu"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=1.0.0b1.dev2026042317,<2"
